docs: Explanation of shard-awareness
scylladb/cpp-driver pull request #19
Opened 2021-01-18 15:47 UTC by jul-stas

Added shard-awareness to the toplevel docs and fixed a few references.

2021-01-19 18:11 UTC, jul-stas commented
Sorry for nagging but ping.
I must close it by the end of the week...

2021-01-19 20:32 UTC, fruch commented on topics/README.md
> +will fall back to the "basic" mode.
Is this fallback automatic ?

2021-01-19 20:34 UTC, fruch commented on topics/README.md
> +Scylla is built around the concept of "sharded architecture". What it means for
How about having an example snippt of code ? Of how shard aware should be used ?

2021-01-19 21:43 UTC, jul-stas commented on topics/README.md
> +Scylla is built around the concept of "sharded architecture". What it means for
I think it's there, in the modification of the example code. Maybe not clear enough (?)
BTW. thanks a lot for chiming in (!)

2021-01-19 22:26 UTC, fruch commented on topics/README.md
> +Scylla is built around the concept of "sharded architecture". What it means for
BTW, I guess you seen that part in the python driver docs: https://python-driver.docs.scylladb.com/stable/scylla_specific.html#shard-awareness

maybe it's not the best example, but something in that direction. 

I don't think we a very long explanation, and we should stick most of it to scylla-core, since it's shard among the drivers, we don't need to keep explaining shard aware again and again in each driver repo

also link to Alexys videos on the the python-driver, might be also helpful
https://github.com/scylladb/python-driver/issues/92 (open an issue to myself to do exactly that)

2021-01-19 22:30 UTC, fruch commented on topics/README.md
> +[`CassCluster`]: http://github.com/scylladb/cpp-driver/tree/master/api/struct.CassCluster/
all those links are broken, it's links to autogenerated docs

check with @dgarcia360 how where to point those links, and how

2021-01-19 22:32 UTC, fruch approved these changes
LGTM, but I would check with @dgarcia360 how the docs are created, and only then handle link fixes.

2021-01-20 09:53 UTC, piodul commented on topics/README.md
> +  /* It is beneficial to set this number to a multiply of node's shard count */
Also, why is it beneficial? Maybe it's worth explaining it here (briefly).

2021-01-20 09:53 UTC, piodul commented on topics/README.md
> +will fall back to the "basic" mode.
Sections about "basic" and "advanced" shard awareness are missing an explanation _why_ the advanced method is better than the basic one.

2021-01-21 06:58 UTC, jul-stas commented on topics/README.md
> +will fall back to the "basic" mode.
yes

2021-01-21 07:00 UTC, jul-stas commented on topics/README.md
> +Scylla is built around the concept of "sharded architecture". What it means for
I've been thinking about it but, sadly, I don't know of a one-to-rule-them-all resource at scylla core. Maybe we should write an ultimate blogpost about shard-awareness?

2021-01-21 07:31 UTC, jul-stas commented on topics/README.md
> +[`CassCluster`]: http://github.com/scylladb/cpp-driver/tree/master/api/struct.CassCluster/
Ooops. For now I'm reverting to datastax docs.

2021-01-21 07:32 UTC, jul-stas commented on topics/README.md
> +  /* It is beneficial to set this number to a multiply of node's shard count */
Done + I chose not to dive into it and just described what will happen.

2021-01-21 07:32 UTC, jul-stas commented on topics/README.md
> +will fall back to the "basic" mode.
Done

2021-01-21 08:36 UTC, lauranovich requested changes

2021-01-21 08:36 UTC, lauranovich commented on topics/README.md
>  application should create a single session object per keyspace as a session
```suggestion
application should create a single session object per keyspace. A session
```

2021-01-21 08:36 UTC, lauranovich commented on topics/README.md
>  I/O threads. More DataStax driver best practices can be found in this [post].
```suggestion
I/O threads. 
```

2021-01-21 08:36 UTC, lauranovich commented on topics/README.md
> +Scylla is built around the concept of "sharded architecture". What it means for
```suggestion
Scylla is built around the concept o a *sharded architecture*. What it means for
```

2021-01-21 08:38 UTC, lauranovich commented
For shard awareness and other Scylla only features use a similar format to 
https://python-driver.docs.scylladb.com/stable/scylla_specific.html and https://python-driver.docs.scylladb.com/stable/scylla_specific.html#shard-awareness

2021-01-25 08:33 UTC, jul-stas commented on topics/README.md
>  established does not alter the session's configuration.
That's how they wrote it in the original docs.
Anyway, I'm afraid I don't understand. Do you mean that changes to the Cluster object are taken into account when the next session is opened?

2021-01-27 11:14 UTC, lauranovich commented on topics/README.md
> +[`CassCluster`]: http://github.com/scylladb/cpp-driver/tree/master/api/struct.CassCluster/
@jul-stas - let's get this merged so I have a stable version and then I can make other changes to the links

2021-01-27 11:15 UTC, lauranovich commented
@jul-stas - if everyone has reviewed and signed off please merge all Docs PRs. I'll do a complete copyedit and link redirect in a separate PR.

2021-01-27 15:07 UTC, merged